[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "336afdda36be888fce47a94a03cadefe3554dfee"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "f037294221d75ff3da4f77f8610b296b7e50461430f5497f3811d834a1a751ea"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "5df28fe4af070c277bf45a6cd70f667d5f0ef3cc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "e948b95eb198d8738815483a605a8d762f16657d73eae16ab00494fccfc5548a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "4748ec0e279078b7ef65468462324b74366f470b"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "6cddc35529bc463e0c7e00a19cb660d9d02a5c165abc3f2ced5fed01c63d248e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "34d2c3933a890b8a376f09ba18b24b8b75f63be9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "f7b18682ba2934ef4d297ee3a9361620c211c987a38c4caeb9b3e87a3165fc17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "530415a6871a7d38a36dace5d442dee8441194f4"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "1b25575df31085c71636dc8bc7d7b5041e91c03c1bda0da2b598aac5a44fad58"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "cd5647def18f553fff9047a6b403732cd60c2df6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "610223d83b4180674276947f2e354338e857b3ac36c224d650fcc488d47d0c00"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "8c3c13fc56e06df833081e7d10ce07b3708195a4"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "cd63de2596103017dee1d7e22c74f96797b97c582aad7e43ab839efa4bad8f98"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "786626f4483f8bce91ec304d79e0390896db8639"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "68a2b50f4c22256e8b697bb8e21e16b3a3cbdf744fe0aede91faedb76b1be9f7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.100+0/GAP_pkg_io.v400.900.100.x86_64-unknown-freebsd.tar.gz"
