[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "075cfe2eea8ed49e90882eebfe610ae515a545de"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "7ca83e89f829f712c97e14b16b353b77c98769450c3b4666342349868b87caad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "d81413484105da47dd10b39296268eb6516e369e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "b568e5479530bdad91d4770f41a5c4ae300a38303f23cafc93bef95aceb36f04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "cf1aac9e70146b75a75123db2e6dded20f50e4b5"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "6559fa1fb6a8d7e7a8c8c594f53b60dd5f79f93a2839ed4eecbdca22619f7d10"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "2fa80cf306b2778f6b2f121dda75a7b8bd14b9ca"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "c363843f66f58f9e4c8eb030242f8e5b86ba7a63e5b753aa2475234f040183e6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "1611afa6fe5e160b71add9b1a92698a1ccf077e5"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "ba45cc6af7d217ee212a3aa674fbe5eba5d6015d6e5e364ec6ba921485e1a7ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "c875b15cadfcfe43e44c8c2c85f43f307145f7f9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "adc3cc3e83890129f5856bef6ec6bda07d9f99f122f771001849569f4bd27ef4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "c9cd860362b558bbb2c20def0b5ed620f5f8a741"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "749e938289a1ec61b7cfd63213fe71f93b0ae955b36b438345f9ab6e8aa55784"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "e70e756e443091cc7cea671b4702e7149aa13452"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "09009636ee5b4beb9c8f87e6eaf37c7b17a116348c8cde9f91fc30ee2492f41b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+1/GAP_pkg_io.v400.700.200.x86_64-unknown-freebsd.tar.gz"
