[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "675b8ff3f2f47f1a1aed4723066cf80896bae3d2"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "0aff861deb5cf073657d0b0cf748f13450014fc5facc4f928d3b3d2177697da7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "19a9962bb1f69e161ac14e70878c1f86c5eb6195"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "b7c8c0dd533d4facaef7228d42f5a325393518ad47a6399074cc059f0150c5bc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "e896ba365aadbfced14a4b3401b00160465d2c4f"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "42be6e83f61ab8bcce18812fa457c122e8bfd08d81ab004bffd50a655dc3a979"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "07f7b93f196683840bb83912b05f0ea168f1be71"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "0f66780d5b6dbd765884e47e68e33af08d57c5f761b79c8fa9b2580b9db87043"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "ec36008c8197a87857744f6d834cf5df482e053b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "8e79114d016f4dd114cb36a5904135cd22f01e7c14c8dd6218d1ab4aadda127a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "riscv64"
git-tree-sha1 = "4f5aa99a18ecf36089762b1de9821b6c460ee95c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "50696a206a8a8a92e712c0fdcfcfea3bde44c9b6b685981f141ff6f17d5de375"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "adc72e6557fc3adf9d53bc56171ffd5a89b70c11"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "f100f38337b7f8266e5bf014c275b75bc72dc587896c30679ad2cefcb17d019a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "8196bfa3e99b50d29f53770796cd3524c8f85a7d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "3d03520ed410f81a52962c396136c0ca008bee563f2f72a411a9a65463e1ed16"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "0169ac0d2eeb13e36ad729b4f55a4c3d2c5b5ffc"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "5010213f018fac3a56f44fa9c340362dd490cd6d49276dd3cedf0dc2bde98eda"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "bc074f081fe2fc4cecc16b985e6cf3ec6f563a57"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "9c78fe3473ac0209bb32e10b7bcd3a5451a405bdb3e0d63bcbc68c14a7bd90c0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.900.102+0/GAP_pkg_io.v400.900.102.x86_64-unknown-freebsd.tar.gz"
