[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "3113a78d2ebd459c85c896efb80791adacab799c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "e151d9b5ec9483d0bf40b7aeba138096b83a5307a00e2f83f6e884ac53cc9e87"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "5a51e0ecb1e1f689f3e1fe44a369bb13c3619e46"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "74d00478d82aba57c196e496752033f2fd41e944f5225375072ed4f440daf8b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "a442e4cca0f967cdfb3bb9f2693b8a540c4754ad"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "9b017c091135fc42acce9c993e1f7f588e501d3ea6903da7c257e22e56da2b0c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "2afc8ed1d70e657febacafc89dc5f09a96b6914e"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "007bf1a76cbe1ab2d88b10bec5d8e3f4558a2ef237c88bacfc4d5c7172bced23"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "f1b8eae4a47074c61b04cfc9599bcc718108484d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "6aae5e14ef5284b03f545ea53c12d94e411ebba367b9040d78e6de439344af9d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "3dfce0ed93e3a1a62b04c5b770a04302d357bdbc"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "0915630aade3ace1d242b779a4cb43d3d97b965dab93e1925d0dba93b5f07219"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "906f5180805ba815a699f804e79391dcb08995d5"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "70e4090e1554d9f4194d1828be172ff12599d744f720e4b3ac9569a337b409c0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.200+0/GAP_pkg_io.v400.700.200.x86_64-unknown-freebsd.tar.gz"
