[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "d1d3248a14ef24dbccaa3528fe4511d5dbce10f9"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "5d96e4c6e665c7006dc21fc2e1f0873eff54ebe52f96c0505d2fbbaafdfe0a2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "c64a4466bcf562e75a60bc373985fe53361b4712"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "465ded5563cd97cdf1be8f9577528bc7fbc29d4179c05c8442afe906fc6abef7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "26ab8f06e239ecb3afc5f12450d4385cd66d52c3"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "e12d655e70ed6e1587dde5bca7c3f6f7b85a23826efa2be0d0141c82282e2202"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "cb713506fc24815d4d4e0d9ea1329e92c5c55be2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "aa2a3ae5d3592902165502a062b7a39cc66aafe86e35aa718ac9ddb7b7856db8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "679ef635df2bf08562b7a2a5566a40386f7eea69"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "e81f09e53db676f1a78618c6d73f0f0e401a10aac9289d8234a9548785a588bc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "250363ce50ac04ebbcc8be8a3622128d6d7f2fe1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "a96401a2f50c478b2404bf620531fd7ec504589df99e0656f60f94973e638d88"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "b18741378cfe562061774703a28466b587e7a9a4"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "e7065c49aa04d4e7b8efef90a466f3bfc1fe158716c8ee40ded45334bcdc4244"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "27a274a409fae6d3f5ee1da7c7740f6cdeb10698"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "f2d4ba1f1e79b3de071655165eb0892eb0823d802525f5d40716488216f3f657"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.201+0/GAP_pkg_io.v400.700.201.x86_64-unknown-freebsd.tar.gz"
