[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "7c3b408be009be10aeee33ca8461ad444516c73e"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "4adf93ad14ec00a9a3e8f61abb6382dca364522be1f0d7c14d16425539b8f28d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "7e47f3d7f72d2922d92fc8da4a417b600f6a4fba"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "8dc1287cf78f93296822bdbe3c8273ca07a4e0cd3c4efd7083f69b15a21571ab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "78df3454fa34374e222872cf71ffeb82141e1db4"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "4cfbb888434bd161ec4bc3dffec8b13feda62fb61f2aa4a637c75e114e9acf5e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "cc234da783c8d586dc7bb40adf19c0332d46d0b1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "7a993991a4845dd299f5fd792dc3973c566a19475be87153042483f75f3367d7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "fe025d85201c83819133a0284429e139342d3eca"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "2f3d1cef2ed6d10dc955554112ad3578f7f17f537053b9085b36563191fb6c89"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "9e534aad19a4364fe7df039425c89f2c77e9008a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "8d21e5baee8abecc113a2ca38dbd97847cc5f17c175f7895a5da9abe485da548"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "2bef009099579aa069b55197eb994924233cd350"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "d96431629582f65d23bb994e1396ccc427fa285cfb503748164af114d208e7e8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "6cf889d0c5dabf45dbc7098adedc60a7101e9261"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "66a8081f423399344627ec6046e80ac82a7f31731e85ec30cf8c3ec595f37fdd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.0+1/GAP_pkg_io.v400.800.0.x86_64-unknown-freebsd.tar.gz"
