[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "974e90649727a3fdb3a8c5dfc6e692f7c575b9d1"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "8625a3c0e9cf40c480359eb356c99529454cc230052f2225b805ab28b073d4a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "a30aa1d1b838ba71e6410865904ef2ea19f1b6ce"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "c5779222e2753b303c48cdc5b376ae855cf20fc9d5ea378620e4c97fd2aed840"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "8e08efa4e3b17530edb8cab01ddb61d5ecfde09a"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "2737c2478aae6e0e4c5716dae0e163f29123971fbadd3bfeb6ad64712bdf1c54"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "e0f468c416afb08c36421e6a8aadb1be7dedd63b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "3f7024699ad928cfb62ee636ec6ccb9f377b4ac37fef56fd7034492ccf8b3e1c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "847c25bea2d45dd5a7625c3654bb4fd5e61e9981"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "7a0cadd066406464d3c03e7ddbc4ea822e26408519c1a0bf9fbe0c132ff98e2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "3ed5b118faabe301447704b57b07010b033ac225"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "864a5167caaf642fdd8b41ce75590b1c5927221d6e2625273e1a4404a4fb48c7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "c310e5e44f33c49dc6da6f2da1164908df30905b"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "5b2fa7a48a15e957de0744be284cba8b8cc18896868ea0ded464645231d6d6fe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "a4b8452aafc79cf53a3c3f7cf8a4195988074a94"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "4b32f80f869e84daabc75f9ba02357f5b001bd241a9521c46e4192fa146c452e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+0/GAP_pkg_io.v400.700.202.x86_64-unknown-freebsd.tar.gz"
