[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "21fc948f2b79050893c96e7e37ab046f801dc12d"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "48c414aae96b0ba959977d523eff281311b083823c487061c3c189a1c744802d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "3350dd0aeddf0df3944c11f0c198855b67992eca"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "a7bf0a7a6fcf2b22cfb2bccbc755b8aea498521f61f35e0a4505138060214454"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "32737da0204e0a0cef6c5922d6c0b4117e58b1af"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "3b6371e59f8f635e13f64f167d6095f749dc839578187b1f3ee688fa3d9bffea"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "5d53cd494edb625e16ffd894bd7fe315921dd893"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "6b4360ff80917bbe43c2ecf95167cf1d4b59fd682104ab10ee5d6496c77a39e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "350d4f95af454e1a85fd75924ae703410fba8a9e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "bbd2e4a45b3ae879c9a9e419290fc9ee1b063bab9e75a4c83e2ba80c135de10e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "riscv64"
git-tree-sha1 = "1178325ae8833ba98c164933a2fdfe88dc7b1a5e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "570b354bf4744ba71f4259f693c3d46fad160d7d79da7a4c9fcec28309130fc5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "d16094ac5e4bd00133c3279342fb640e444fe880"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "b20f5e43207616b05fa27e2e56ba92564d4c8d23b910ead6554987ecff1ee79c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "c8e09ff2c201ba8d0a9d455881fa6cd55cb9e685"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "490c657c88fa6f3c9b539bf54dca2e1de90c67ab9b83a9c4acfea07155ff997b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "2233b9b525c10d299fb42cf77b59ea04d4ed4bf7"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "c2f77c7da068a9144e9aa18d6592aa067f5161f73e12111db6ad58124099aa71"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "21c45e23f6b496aa83eb7975b3597c33b92fd824"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "cf3429c283f85861f4a2b55d6b4317908536735624da242e2bdc2969c482a48c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v401.90300.1+0/GAP_pkg_io.v401.90300.1.x86_64-unknown-freebsd.tar.gz"
