[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "a51274667dfce0ad42253f5afa308a2f109b5c33"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "2b76539083687e736dbb71f054cbdef891fd1d6419603cdd81c6ef548b01fb8c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "8bd5ca5c6bd8c66da341e2737882c0621cf20d0a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "82b9057a92922b2ed479103fd01c735190483159bb20c13eeb783144c2090441"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "5d04eb6498a473388281170abb9874674be5cb56"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "ae61f870e9233a3fd6e88108df0b8fa0d6e366679260bdd5af97771bfa22f60b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "f7904497feaca802a0d9ff8987cd88d16727450b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "8a78ba38df40e0bf56f705d964f57dc519478aa2db7d3489a161e6fe6e0b3b7b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "f8b9b5e1c7b805e5d380a1d23ba2aed9827090f7"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "d8844cfd1fd830fa2cef5a097b1af2758ebabef14ea09d6ab29755be2d7056a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "4b8722d1610ef6af2c12fb68b045d296b5f05754"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "eaa3eae305a4eed905058286d6f094bb8eb1ea78a00691a1f6d85b469ab31fe7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "6686a889eea9eadc21b842aadd7369406a75c2a5"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "5372372803264cd8e0b19721fba515a117450950fe1547dc0f1c68fb99fb0739"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "52f7ade39ad130af39d774f3c0be4520cdf35176"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "8d46363303da0669a9615003e951eadd9d4a93fb021d2c2cbc57664bb7f463cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.700.202+1/GAP_pkg_io.v400.700.202.x86_64-unknown-freebsd.tar.gz"
