[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "776775d9e07cfc48809e8d69a7d9253803073309"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "3b4f7c9224a2a050a63699a60cda4da13fabb6b9951a4c267f704147f076d50c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "9681782d3f353b646042a059bc04a0d1c143c321"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "8591b9a6f26f3048479bcac576e58f646ca031c3bfcbe0298ff8815536dae739"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "aarch64"
git-tree-sha1 = "ab4de79cdd0e2c38dcdd880c4fa2c61c6bc826c1"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "a4cce34e43b87e9a3e68ef7eeedb3c675cb7037d5f2928bd915118cd1baef080"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.aarch64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "powerpc64le"
git-tree-sha1 = "2b3ca649e69082ca1916c8d27a30f19bc6558e65"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "eba5df0ec845a1a620ba29a04879b42200ecf9cbd217957469b260d60420f224"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "9f79b03135159d47c54968109b447ca7a557f9ff"
os = "macos"

    [[GAP_pkg_io.download]]
    sha256 = "b7f58249719cce3a4ad361935e70c6f43bc5ca36874ba137f81e99ccc2a2f453"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "abb631fa8b6397cd355f4eeff34319aab7f93dff"
libc = "glibc"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "3fdb90ad7d55b584bb8b1dc22a59257fee3c0893832ae33b9a5102959ec0c7f1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "7206a95813591ce3f87785aeb17fbe96a3837119"
libc = "musl"
os = "linux"

    [[GAP_pkg_io.download]]
    sha256 = "85ebad457889daae9fcef701126b94a6da3e9c7e54d5cff62a76177399c727a2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.x86_64-linux-musl.tar.gz"
[[GAP_pkg_io]]
arch = "x86_64"
git-tree-sha1 = "0e531d8ab46219179b74ef91180475f3047ee9c6"
os = "freebsd"

    [[GAP_pkg_io.download]]
    sha256 = "53289fcf62d09ce5c34307a3a34de48d82eb384963d0abe4e36a6c23b00d5622"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_io_jll.jl/releases/download/GAP_pkg_io-v400.800.200+0/GAP_pkg_io.v400.800.200.x86_64-unknown-freebsd.tar.gz"
